#ifndef CONSTANTS_H
#define	CONSTANTS_H


#define I2S_WORD_LENGTH 16

#define BUFFERBYTES 512
#define BUFFERLENGTH 256
#define BUFFERLENGTH_DIV_2 128

#define FCY 69120000UL
#define FCY_STARTUP 3650000UL

#define PCM 1
#define PCMSIZE 16
#define CHANNELS 2
#define BITS_PER_SAMPLE 16

#define DCI_BCG_VALUE ((FCY/(2*CODEC_SAMPLE_RATE*2*I2S_WORD_LENGTH))-1)

#endif	/* CONSTANTS_H */

